<div class="o-canvas o-canvas_max-width918">
    <div class="is-active">
        <header class="o-header-img u-margin-top-56 u-margin-bottom-56">
            <img 
                class="o-header-img__brand o-header-img__brand_w255" 
                alt="Personas conectadas a internet" 
                src="<?= $this->getViewFileUrl('images/people-mobil.svg') ?>"
            >
            <h3 class="o-header-img__text o-header-img__text_font40 u-margin-bottom-8">¡Felicidades!</h3>
            <h1 class="o-header-img__intro">
                Gracias por confiar en nosotros. <br>
                En breve recibirás un correo con la confirmación de tu compra.
            </h1>
        </header>

        <ul class="c-figures-columns u-margin-bottom-56">
            <li class="c-figures-columns__column">
                <span class="c-figures-columns__figure i-pin-way"></span>
                <div class="u-text-center">
                    <h4>Dirección de Instalación</h4>
                    <p class="c-figures-columns__text">Transversal 60 Cl 114 A - 55 Julio Florez - Suba</p>
                </div>
            </li>
            <li class="c-figures-columns__column">
                <span class="c-figures-columns__figure i-calendar-strong"></span>
                <div class="u-text-center">
                    <h4>Fecha de Instalación</h4>
                    <p class="c-figures-columns__text">26/02/2022       7:00 a.m. - 12:00 p.m.</p>
                </div>
            </li>
        </ul>

        <section class="u-margin-bottom-56">

            <h2 class="o-title">Resumen de tu compra</h2>
            <div class="o-section-double-elements o-section-double-elements_spacebetween o-section-double-elements_flex-start o-section-double-elements_row-gap">
                <div>
                    
                    <dl class="c-definition-list">
                        <div class="c-definition-list__box">
                            <dt class="c-definition-list__term">Servicio:</dt>
                            <dd class="c-definition-list__def">Trío voz ilimitada Nacional 200 min LDI Banda Ancha 150 Mbps Plus_Fibra TV_RV_15017, Netflix HD 2 pantallas.</dd>
                        </div>
                        <div class="c-definition-list__box">
                            <dt class="c-definition-list__term">Servicio Adicionales:</dt>
                            <dd class="c-definition-list__def"></dd>
                        </div>
                        <div class="c-definition-list__box">
                            <dt class="c-definition-list__term">Nombre:</dt>
                            <dd class="c-definition-list__def">Marcelo Montero López</dd>
                        </div>
                        <div class="c-definition-list__box">
                            <dt class="c-definition-list__term">Documento:</dt>
                            <dd class="c-definition-list__def">Cédula 123456788</dd>
                        </div>
                        <div class="c-definition-list__box">
                            <dt class="c-definition-list__term">Número de Orden:</dt>
                            <dd class="c-definition-list__def">20000600685569</dd>
                        </div>
                        <div class="c-definition-list__box">
                            <dt class="c-definition-list__term">Fecha de compra:</dt>
                            <dd class="c-definition-list__def">27 de septiembre de 2021</dd>
                        </div>
                        
                    </dl>

                </div>
            
                <div>
                    <div class="c-card-summary c-card-summary_padding16 c-card-summary_margin-top is-summary-show">
                        <div class="c-card-summary__amount c-card-summary__total c-card-summary__total_margin0">
                            <h4 class="u-uppercase">Total</h4>
                            <p>1399, 90 $</p>
                        </div>
                    </div>
                    <div class="u-margin-top-16">
                        <p>Deseas una copia de tu orden de compra</p>
                        <a class="o-btn o-btn_secondary o-btn-icon i-clip u-margin-top-16">Descargar PDF</a>
                    </div>
                </div>
            </div>

            <div class="u-text-center u-margin-top-32">
                <a class="o-btn o-btn_full o-btn_w255 o-btn_height56" href="#">Volver a Inicio</a>
            </div>

        </section>

    


    </div>

</div>