<div>
    <fieldset class="admin__fieldset" id="content-auto-sort" style="display:none;">
        <div class="admin__field">
            <div class="admin__field-label">
                <label for="autoSort" ><span>Auto Sort</span></label>
            </div>
            <div class="admin__field-control">
                <select class="admin__control-select" data-subcategory="null" data-category="null" id="autoSort">

                </select>
            </div>
        </div>
    </fieldset>
    <div class="list" id="sortElementsOfferts">
    </div>
</div>
<script>
    require([
        'jquery',
        "prototype"
    ], function ($) {
        window.subOffert = '<?= /** @noEscape */ $block->getUrl('fija/sortofferts/offert')?>';
        window.getOffert = '<?= /** @noEscape */ $block->getUrl('fija/sortofferts/getofferts')?>';
        $(document).on("change", "#autoSort", function(){
            let value = $("select[name='type_id']").val();
            autoSort = $('#autoSort option[value='+$(this).val()+']');
            let typeSort = autoSort.data("type");
            let subcategory = autoSort.data("subcategory");
            let category = autoSort.data("category");
            let attr = autoSort.data("attr");
            $.ajax({
            showLoader: true,
			method: 'GET',
			url: '<?= $block->getUrl('fija/sortofferts/automatic') ?>',
			data: {
                typeSort: typeSort ,
                attrSort: attr ,
                id_category: category,
                id_subcategory : subcategory
			},
			dataType: 'json',
            }).done(function(data) {
                reloadOfferts(value);
		    });
        });
        function reloadOfferts(value){
            let list = document.getElementById('sortElementsOfferts');
            let autoSort = document.getElementById('autoSort');
            let contentAutoSort = document.getElementById('content-auto-sort');
            let completeAutoSort = false;
            list.innerHTML = '';
            list.style.display = 'block';
            contentAutoSort.style.display = 'none';
            $.ajax({
                showLoader: true,
                method: 'POST',
                url: getOffert,
                data: {
                    value: value ,
                },
                dataType: 'json',
            }).done((function(response) {
                if(response) {
                    response.forEach(element =>{
                        if(element.status != 0) {
                            if(element.value != 0){
                                if(!completeAutoSort){
                                    autoSort.innerHTML = `
                                        <option data-type="desc" data-attr="0" data-subcategory = "NN" data-category= "NN}" value="NN"  disabled="true" selected="selected">Select Type Sort</option>
                                        <option data-type="desc" data-attr="price" data-subcategory = "${element.id_subcat}" data-category= "${element.id_cat}" value="desc_price">Higher Price</option>
                                        <option data-type="asc" data-attr="price" data-subcategory = "${element.id_subcat}" data-category= "${element.id_cat}" value="asc_price">Lower Price</option>
                                        <option data-type="desc" data-attr="title" data-subcategory = "${element.id_subcat}" data-category= "${element.id_cat}" value="desc_title">Higher Title Speed</option>
                                        <option data-type="asc" data-attr="title" data-subcategory = "${element.id_subcat}" data-category= "${element.id_cat}" value="asc_title">Lower Title Speed</option>
                                    `
                                    contentAutoSort.style.display = 'block';
                                    completeAutoSort = true;
                                }
                                if(value != 0){
                                    list.innerHTML += `
                                        <div data-subcategory="${element.id_subcat}" data-category="${element.id_cat}" data-id="${element.value}">${element.label} </div>
                                    `;
                                }else{
                                    list.innerHTML += `
                                        <div data-id="${element.value}">${element.label} </div>
                                    `;
                                }
                            }
                        }
                    });
                }else{
                    contentAutoSort.style.display = 'none';
                    list.innerHTML += `
                    <div>Empty</div>
                    `;
                }
            }).bind(this));
        }

    });
</script>
