<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Catalog\Block\Product\View\Details $block */

$_helper = $this->helper('Vass\Custom\Helper\Data');
$atributes = explode(',',$_helper->getAttributes());
$product = $_helper->getProduct();

?>
<div class="product info detailed">
    <div class="row justify-content-center justify-content-sm-start" >
        <?php
        foreach($atributes as $key => $value){
            if(!empty($value)){
                $dataParts = explode('--',$value);
                /*echo '<pre> ';
                print_r($dataParts);
                echo '</pre> ';*/
                $attValue = $product->getAttributeText(trim($dataParts[1]));
                if(!empty($attValue)&&$attValue!=''){
                ?>
                    <div class="col-5 col-sm-2 bg-white icons-attributes mt-2 mb-2" >
                        <img class="button5 mab-3 icons-img" src="<?php echo $block->getViewFileUrl('images/'.$dataParts[1].'.png');  ?>" >
                        
                        <h3 class="subtitle-1 text-azul-oscuro m-0"><?php echo $dataParts[0] ?></h3>
                        <h4 class="body-4 text-gris-5 m-0"><?php echo $attValue ?></h4>
                    </div>
                <?php
                }
            }
        }
        ?>
    </div>
</div>
<?php if ($detailedInfoGroup = $block->getGroupSortedChildNames('detailed_info', 'getChildHtml')) :?>
    <div class="product info detailed">
        <?php $layout = $block->getLayout(); ?>
        <div class="product data items top-50 start-50 translate-middle" data-mage-init='{"tabs":{"openedState":"active"}}'>
            <?php foreach ($detailedInfoGroup as $name) :?>
                <?php
                $html = $layout->renderElement($name);
                if (!trim($html)) {
                    continue;
                }
                $alias = $layout->getElementAlias($name);
                $label = $block->getChildData($alias, 'title');
                ?>
                <div class="data item title"
                     data-role="collapsible" id="tab-label-<?= $block->escapeHtmlAttr($alias) ?>">
                    <a class="data switch"
                       tabindex="-1"
                       data-toggle="trigger"
                       href="#<?= $block->escapeUrl($alias) ?>"
                       id="tab-label-<?= $block->escapeHtmlAttr($alias) ?>-title">
                        <?= /* @noEscape */ $label ?>
                    </a>
                </div>
                <div class="data item content"
                     aria-labelledby="tab-label-<?= $block->escapeHtmlAttr($alias) ?>-title" id="<?= $block->escapeHtmlAttr($alias) ?>" data-role="content">
                    <?= /* @noEscape */ $html ?>
                </div>
            <?php endforeach;?>
        </div>
    </div>
<?php endif; ?>
