<?php
    $_productCollection = $block->getLoadedProductCollection();
    if ( !$_productCollection->count() ):
        $_productCollection = $block->getLoadedProductCollection();
        $helperCustom = $this->helper(Vass\Custom\Helper\Data::Class);
        $helperCuotas = $this->helper(Vass\Config\Helper\Data::Class);
        $cuotas = $helperCuotas->getCuotas();
        $_helper = $block->getData('outputHelper');
        $products = $helperCustom->getProductsResulSearch();
        $image = 'related_products_list';
        $optionsMarca = $helperCustom->getAttributesByCode('marca');
        $enabledBrandsSearh = $helperCustom->brandsEnabledSearch();
        if ($block->getMode() === 'grid'):
            $viewMode = 'grid';
            $imageDisplayArea = 'category_page_grid';
            $showDescription = false;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
        else:
            $viewMode = 'list';
            $imageDisplayArea = 'category_page_list';
            $showDescription = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
        endif;
        $pos = $block->getPositioned();
        if($products->count() > 0):
?>
            <div class="o-layout-noresults <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?>">

                <div class="c-list-links">
                    <h3 class="c-list-links__title">Intenta probar con una búsqueda más simple</h3>

                    <nav class="c-list-links__nav">
                        <?php 
                            foreach ($optionsMarca as $key => $option): 
                                if($option->getValue() != '' && in_array($option->getLabel(), $enabledBrandsSearh)):
                        ?>
                                    <a class="c-list-links__link o-link i-arrow-right" href="<?=$block->getBaseUrl()?>?marca=<?=$option->getValue()?>">Celulares <?=$option->getLabel()?></a>
                        <?php 
                                endif;
                            endforeach;
                        ?>
                    </nav>
                </div>

                <!-- Slider related products -->
                <section class="o-section">
                    <div class="o-canvas">
                        <div>
                            <h4 class="o-title o-light">¡O descubre grandes ofertas en nuestra tienda!</h4>

                            <div class="js-slider-product-wrap u-position-relative">
                                <div class="c-slider-products swiper js-swiper-cards-product">
                                    <div class="swiper-wrapper">
                                        <?php
                                            $index = 0;
                                            foreach($products as $key => $product):
                                                $price = $product->getPriceInfo()->getPrice('regular_price')->getValue();
                                                $sprice = $product->getPriceInfo()->getPrice('final_price')->getValue();   
                                                //$product = $helperVass->getProductAllOptions($product->getId());
                                        ?>
                                        <div class="c-card-slide swiper-slide">   
                                            <article class="c-card">
                                                <a
                                                    class="c-card__link"
                                                    id="product-item-info_<?= /* @noEscape */ $product->getId() ?>"
                                                    data-container="product-<?= /* @noEscape */ $viewMode ?>"
                                                    data-product-name="<?= /* @noEscape */ $product->getName() ?>"
                                                    data-product-id="<?= /* @noEscape */ $product->getId() ?>"
                                                    data-product-price="<?= /* @noEscape */ $product->getFinalPrice() ?>"
                                                    data-product-brand="<?= /* @noEscape */ $product->getData('marca') ?>"
                                                    data-product-category="Equipo"
                                                    data-product-variant=""
                                                    data-product-dimension18="catalogo-general-Terminal Libre"
                                                    data-product-dimension26="<?= /* @noEscape */ 
                                                    abs(round((($sprice - $price) / $price) * 100, 0)) ?>"
                                                    data-product-dimension27="<?= /* @noEscape */ $product->getName() ?>"
                                                    data-product-position="<?= /* @noEscape */ (string)(++$index) ?>"
                                                    data-is-viewed="n"
                                                    href="<?= $escaper->escapeUrl($product->getProductUrl()) ?>"
                                                    title="Ver detalle de <?= $escaper->escapeUrl($product->getName()) ?>"
                                                >
                                                    <?php
                                                            $productImage = $block->getImage(
                                                                $product,
                                                                $imageDisplayArea
                                                            );
                                                            if($pos != null):
                                                                $position = 'left:' .
                                                                $productImage->getWidth() . 'px;' . 'top:' . $productImage->getHeight()
                                                                . 'px;';
                                                            endif;
                                                    ?>
                                                    <div class="c-card__photo" tabindex="-1">
                                                    <?= $productImage->toHtml() ?>
                                                    </div>
                                                    <div class="c-card__content">
                                                    <?php
                                                        $attrTextDctoValue =$product
                                                        ->getResource()
                                                        ->getAttribute('text_dcto')
                                                        ->getFrontend()->getValue($product);
                                                        if (!empty($attrTextDctoValue) && $attrTextDctoValue != ''):
                                                    ?>
                                                        <span class="c-card__tag"><?= $block->escapeHtml($attrTextDctoValue) ?></span>
                                                    <?php
                                                        endif;
                                                    ?>
                                                        <?php 
                                                            $productNameStripped = $block->stripTags($product->getName(),null,true);
                                                        ?>
                                                        <h4 class="c-card__name">
                                                            <?= $block->escapeHtml($product->getName()) ?>
                                                        </h4>
                                                        <?= $block->getReviewsSummaryHtml($product, $templateType) ?>
                                                        <?php
                                                            if ($cuotas >= 1):
                                                                $dueprice = round (($sprice) / $cuotas, 2);
                                                        ?>
                                                                <p class="c-card__text">Hasta <?=$cuotas?> cuotas de:</p>

                                                                <h3 class="c-card__dues" data-dynamic="plazos">
                                                                    <?= "$" . number_format(abs($dueprice), 0, ",", ".")?>
                                                                </h3>
                                                        <?php
                                                            endif;
                                                        ?>
                                                        <p class="c-card__text c-card__text_sm">Precio desde:</p>
                                                        <div class="c-card__price">
                                                            $<?=number_format($sprice, 0, ",", ".")?>
                                                            <?php if ($price>$sprice) { ?> 
                                                                <small class="c-card__price-previous">
                                                                    $<?=number_format($price, 0, ",", ".")?>            
                                                                </small>

                                                            <?php    } ?>
                                                        </div>
                                                        <ul class="c-card__schema">
                                                                <?php
                                                                    $swatchBlock = $this->getLayout()
                                                                    ->createBlock(Magento\Swatches\Block\Product\Renderer\Listing\Configurable::Class)
                                                                    ->setTemplate("Magento_Swatches::product/listing/renderer.phtml");
                                                                    echo $swatchBlock->setProduct($product)->toHtml();  
                                                                ?>
                                                        </ul>
                                                    </div>
                                                </a>
                                            </article>
                                        </div>
                                        <?php
                                            endforeach;
                                        ?>
                                    </div>
                                </div>

                                <!-- Navigation buttons -->
                                <span class="o-swiper-chevron o-swiper-chevron_bg swiper-button-prev">
                                    <span class="u-hidden">
                                    Slider anterior
                                    </span>
                                </span>
                                <span class="o-swiper-chevron o-swiper-chevron_bg swiper-button-next">
                                    <span class="u-hidden">
                                    Slider siguiente
                                    </span>
                                </span>
                            </div>

                        </div>
                    </div>
                </section>

                <div class="u-text-center">
                    <a href="" class="o-btn o-btn_w170_mb"> Ir a la tienda </a>
                </div>
            </div>
<?php 
        endif;
    endif;
?>