<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
?>
<p class="c-toolbar__amount" id="toolbar-amount">
    <?php if ($block->getLastPageNum() > 1):?>
        <?= $block->escapeHtml(
            __(
                'Mostrando %1-%2 de %3 resultados',
                '<span class="toolbar-number">' . $block->getFirstNum() . '</span>',
                '<span class="toolbar-number">' . $block->getLastNum() . '</span>',
                '<span class="toolbar-number">' . $block->getTotalNum() . '</span>'
            ),
            ['span']
        ) ?>
    <?php elseif ($block->getTotalNum() == 1):?>
        <?= $block->escapeHtml(
            __('Mostrando %1 resultado', '<span class="toolbar-number">'.
            $block->getTotalNum() . '</span> de ' . '<span class="toolbar-number">'.
            $block->getTotalNum() . '</span>'),
            ['span']
        ) ?>
    <?php else:?>
        <?= $block->escapeHtml(
            __('Mostrando %1 resultados', '<span class="toolbar-number">'. 
            $block->getTotalNum() . '</span> de ' . '<span class="toolbar-number">'.
            $block->getTotalNum() . '</span>'),
            ['span']
        ) ?>
    <?php endif; ?>
</p>
