<div class="container footer-checkout">
    <div class="row mw-100 m-0 px-1 px-lg-0 pat-7 pab-7 justify-content-betwen justify-content-lg-evenly">
        <div class="col-3 col-lg-2 p-0">
            <div class="row mx-1 mx-lg-0 mw-100 m-0 p-0 h-100 align-items-md-center 
                justify-content-center justify-content-md-start">
                <div class="col-12 col-md-4 d-flex justify-content-center justify-content-lg-end p-0 pe-lg-3">
                    <img class="w-img-footer"  
                        src="<?= $escaper->escapeHtml($block->getViewFileUrl('images/discount.png')) ?>">
                </div>
                <div class="col-12 col-md-8 p-0">
                    <p class="body-3 text-white bold m-0 text-center text-md-start p-0">Exclusivo Online</p>
                </div>
            </div>
        </div>
        <div class="col-3 col-lg-2 p-0">
            <div class="row mx-1 mx-lg-0 p-0 h-100 align-items-md-center 
                justify-content-center justify-content-md-start">
                <div class="col-12 col-md-4 d-flex justify-content-center justify-content-lg-end p-0 pe-lg-3">
                    <img class="w-img-footer"
                        src="<?= $escaper->escapeHtml($block->getViewFileUrl('images/truck_blue.png')) ?>">
                </div>
                <div class="col-12 col-md-8 p-0">
                    <p class="body-3 text-white m-0 text-center text-md-start p-0">
                        <span class="bold d-block">
                            Envío GRATIS 
                            <span class="regular fw-normal d-md-flex d-none">a todo Colombia</span>
                            <span class="regular fw-normal d-md-none d-block">y oficial</span>
                        </span>
                    </p>
                </div>
            </div>
        </div>
        <div class="col-3 col-lg-2 p-0">
            <div class="row mx-1 mx-lg-0 p-0 h-100 align-items-md-center 
                justify-content-center justify-content-md-start">
                <div class="col-12 col-md-4 d-flex justify-content-center justify-content-lg-end p-0 pe-lg-3">
                    <img class="w-img-footer" src="<?= $escaper->escapeHtml($block->getViewFileUrl('images/card.png')) ?>">
                </div>
                <div class="col-12 col-md-8 p-0">
                    <p class="body-3 text-white fw-normal m-0 text-center text-md-start p-0 d-none d-md-block"><span class="bold">Difiere </span>con tu tarjeta preferida</p>
                    <p class="body-3 text-white fw-normal m-0 text-center text-md-start p-0 d-md-none">Difiere con tarjeta </p>
                </div>
            </div>
        </div>
        <div class="col-3 col-lg-2 p-0">
            <div class="row mx-1 mx-lg-0 p-0 h-100 align-items-md-center justify-content-center justify-content-md-start">
                <div class="col-12 col-md-4 d-flex justify-content-center justify-content-lg-end p-0 pe-lg-3">
                    <img class="w-img-footer" src="<?= $escaper->escapeHtml($block->getViewFileUrl('images/secure.png')) ?>">
                </div>
                <div class="col-12 col-md-8 p-0">
                    <p class="body-3 text-white fw-normal m-0 text-center text-md-start p-0 d-none d-md-block">
                        Compra de forma <span class="bold">segura
                    </span></p>
                    <p class="body-3 text-white fw-normal m-0 text-center text-md-start p-0 d-md-none">
                        Compra segura
                    </p>
                </div>
            </div>
        </div>
    </div>
    <div class="row mw-100 m-0 border-top border-f-color-white p-0 px-lg-0 pt-lg-2 pb-lg-3 mw-100 m-0 copyright-mv">
        <div class="col-12 col-lg-4 p-0 d-flex align-items-center 
            justify-content-center justify-content-lg-start mb-3 mb-lg-0 mt-2 mt-lg-0">
            <p class="body-4 p-0 m-0 f-color-white">© 2021 Movistar. Todos los derechos reservados.</p>
        </div>
        <div class="col-12 col-lg-8 p-0">
            <div class="row align-items-center justify-content-center justify-content-lg-end flex-wrap flex-lg-nowrap">
                <div class="col-6 col-md-4 col-lg-auto p-0">
                    <p class="border-f-color-white text-center m-0">
                        <a class="border-end body-4 ligth px-1 px-md-2 f-color-white" href="#">
                            Política de privacidad
                        </a>
                    </p>
                </div>
                <div class="col-6 col-md-4 col-lg-auto p-0">
                    <p class="border-f-color-white text-center m-0">
                        <a class="border-end body-4 ligth px-1 px-md-2 f-color-white" href="#">
                            Términos y condiciones
                        </a>
                    </p>
                </div>
                <div class="col-4 col-md-4 col-lg-auto p-0">
                    <p class="border-f-color-white text-center m-0">
                        <a class="border-end body-4 ligth px-1 px-md-2 f-color-white" href="#">Ventas y devoluciones</a>
                    </p>
                </div>
                <div class="col-4 col-md-6 col-lg-auto p-0">
                    <p class="border-f-color-white text-center m-0">
                        <a class="border-end body-4 ligth px-1 px-md-2 f-color-white" href="#">Política de cookies</a>
                    </p>
                </div>
                <div class="col-4 col-md-6 col-lg-auto p-0">
                    <p class="text-center m-0">
                        <a class="body-4 ligth px-2 f-color-white" href="#">Mapa de sitio</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>