<div
    id="modal-decos"
    class="o-modal o-modal_w500 modal u-hidden"
    data-modal-type="modal-large"
>   

    <button
        class="o-modal__btn-close close-modal i-close"
        data-modal="modal-decos"
    >
        <span class="u-hidden">Cerrar</span>
    </button>

    <div class="o-modal__content">

    <div class="o-message o-message_w340">

        <figure class="o-modal__header u-margin-bottom-16">
            <img 
                class="o-modal__img" 
                alt="Logo Movistar" 
                src="<?= $this->getViewFileUrl('images/fija/servicios_complementarios.svg') ?>"
            >
        </figure>

        <div>

            <header
                class="
                    o-message__header
                    u-margin-bottom-16
                "
            >
                <h2 class="o-message__title o-message__title_bold o-message__title_fs18">
                    ¡Personaliza los paquetes que tenemos para tí!
                </h2>
            </header>

            <fieldset class="c-form__fieldset u-width-100">

                <div class="c-form__radio c-form__radio_mb0">
                        <input
                        name="deco"
                        type="radio"
                        value="deco"
                        class="c-form__radio-input"
                        id="deco"
                    />

                    <div class="c-form__radio-box">
                        <label
                            class="c-form__radio-label"
                            for="deco"
                        >
                            Deco adicional IPTV
                        </label>
                    </div>
                </div>

                <div class="c-chips c-chips_border">
                    <div class="c-chips__box c-chips__box_evenly">
                        <div class="c-chips__item c-chips__item_sm">
                            <input
                                value="3"
                                class="c-chips__input"
                                name="cuota"
                                type="radio"
                                id="chip"
                            />
                            <label class="c-chips__label" for="chip">1 Deco</label>
                        </div>
                        <div class="c-chips__item c-chips__item_sm">
                            <input
                                value="6"
                                class="c-chips__input"
                                name="cuota"
                                type="radio"
                                id="chip2"
                            />
                            <label class="c-chips__label" for="chip2">2 Decos</label>
                        </div>
                        <div class="c-chips__item c-chips__item_sm">
                            <input
                                value="12"
                                class="c-chips__input"
                                name="cuota"
                                type="radio"
                                id="chip3"
                            />
                            <label class="c-chips__label" for="chip3">3 Decos</label>
                        </div>
                        <div class="c-chips__item c-chips__item_sm">
                            <input
                                value="18"
                                class="c-chips__input"
                                name="cuota"
                                type="radio"
                                id="chip4"
                            />
                            <label class="c-chips__label" for="chip4">4 Decos</label>
                        </div>
                        <div class="c-chips__item c-chips__item_sm">
                            <input
                                value="24"
                                class="c-chips__input"
                                name="cuota"
                                type="radio"
                                id="chip5"
                            />
                            <label class="c-chips__label" for="chip5">5 Decos</label>
                        </div>
                    </div>
                </div>

            </fieldset>

            <div class="c-card-summary__amount">
                <h4 class="o-text_gray5">Valor</h4>
                <span class="o-text_gray5">$0</span>
            </div>

            <div class="o-message__actions u-margin-top-32">
                <a
                    href="#"
                    class="o-btn o-btn_w255 o-btn_height56 o-btn_height40_mb o-message__btn"
                >
                    Agregar paquetes
                </a>
            </div>
        </div>

    </div>
        
    </div>
           
</div>