<div class="o-modal o-modal_w500 modal  u-hidden" id="modal-alert_accept_terms_conditions" data-modal-type="modal-large"  >     
<button class="o-modal__btn-close close-modal i-close" data-modal="modal-alert_accept_terms_conditions">
        <span class="u-hidden">Cerrar</span>
    </button>
    <div class="o-modal__content o-modal__content_center">

        <div class="o-alert__content">
                <header class="o-alert__header">
                    <h3 class="o-title-ico o-title-ico__red i-information">Información</h3>
                </header>
        </div>
        <div class="o-modal__text-box o-modal__text-box_marginb">
            <p>!Debe aceptar el tratamiento de datos personales, términos y condiciones para continuar.</p>
        </div>
        <footer class="o-alert__footer">
            <button data-modal="modal-alert_accept_terms_conditions" class="o-btn o-alert__cta o-btn_w290 close-modal">Continuar</button>
        </footer>

    </div>
</div>