<div class="o-modal modal  u-hidden" id="modal-alert-change-address" data-modal-type="modal-large" >   
    <button class="o-modal__btn-close close-modal i-close" data-modal="modal-alert-change-address">
        <span class="u-hidden">Cerrar</span>
    </button>
    <div class="o-modal__content o-modal__content_center o-modal__content_w572">
        <span class="o-modal__img-ico i-information"></span>

        <header class="o-modal__header">
            <h3 class="o-headline o-headline_blue">Al cambiar tu dirección</h3>
        </header>

        <p class="c-error-modal__paragraph">
            Podrás realizar el pago de tu equipo unicamente de contado
        </p>

        <footer class="o-modal__footer o-modal__footer_flex">
            <button class="o-btn o-btn_height56 o-btn_full o-btn_w270 o-btn_secondary close-modal" data-modal="modal-alert-change-address">Cancelar</button>

            <button class="o-btn o-btn_height56 o-btn_full o-btn_w270 open-close-modal" 
                data-modal-open="modal-validate_entity_address" 
                data-modal-close="modal-alert-change-address">
                
                Continuar

            </button>
        </footer> 
    </div>
</div>