<div class="o-modal o-modal_w500 modal  u-hidden" id="modal-attention_alert" data-modal-type="modal-small" >     
    <button class="o-modal__btn-close close-modal i-close" data-modal="modal-attention_alert">
        <span class="u-hidden">Cerrar</span>
    </button>
    <div class="o-modal__content o-modal__content_center">

        <div class="o-alert__content">
                <header class="o-alert__header">
                    <h3 class="o-title-ico o-title-ico__red i-information">¡Atención!</h3>
                </header>
        </div>
        <div class="o-modal__text-box o-modal__text-box_marginb" id="alerts">

        </div>
        <footer class="o-alert__footer">
            <button id="closeModal" data-modal="modal-attention_alert" class="o-btn o-alert__cta o-btn_w290 close-modal">Volver</button>
            <a id="redirectModal" style="display:none" href="#" class="o-btn o-alert__cta o-btn_w290">Aceptar</a>
        </footer>

    </div>

</div>