<div class="o-modal modal  u-hidden" id="modal-error-general" data-modal-type="modal-small" > 
        
    <button id="close-modal-error" class="o-modal__btn-close close-modal i-close" data-modal="modal-error-general">
        <span class="u-hidden">Cerrar</span>
    </button>


    <div class="o-modal__content o-modal__content_center">
        <img
            alt="Hombre sentado en el piso con el celular al oido"
            src="<?php echo $block->getViewFileUrl('images/modals/men-figure.svg') ?>"
            class="c-error-modal__img">

        <header class="o-modal__header">
            <h3 class="o-headline">¡Te ayudamos!</h3>
        </header>

        <p class="c-error-modal__paragraph">
            en este momento no podemos atender tu transacción por favor comunícate con nosotros desde tu celular *611 o la línea gratuita 01 8000 930930.
        </p>

        <footer class="o-modal__footer">
            <a class="o-modal__btn o-modal__btn-lh o-btn" id="redirectHome">Volver a la página de inicio</a>
        </footer> 

    </div>


</div>