<div class="o-modal modal u-hidden" id="modal-financing" data-modal-type="modal-small" >
    <button class="o-modal__btn-close close-modal i-close" data-modal="modal-financing">
        <span class="u-hidden">Cerrar</span>
    </button>
    
    <div class="o-modal__content">
            
        <div class="c-pay-methods__row">
            <h3 class="c-pay-methods__title">Financiación a tu factura</h3>
                <div class="c-pay-methods__slot-wrap c-pay-methods__slot-wrap_line">
                    <div class="c-pay-methods__slot c-pay-methods__slot_row c-pay-methods__slot_line">
                        <span class="c-pay-methods__ico i-paper"></span>
                        <div class="c-pay-methods__content">
                            <h4 class="c-pay-methods__subtitle">Paga con tu factura</h4>
                            <p class="c-pay-methods__description">Financia tu equipo en tu factura Movistar</p>
                        </div>
                    </div>                   
            

                    <div class="c-pay-methods__slot c-pay-methods__slot_row">
                        <span class="c-pay-methods__ico i-movistar-money"></span>
                        <div class="c-pay-methods__content">
                            <h4 class="c-pay-methods__subtitle">Movistar Money</h4>
                            <p class="c-pay-methods__description">Financia tu celular 0% de interés a crédito.</p>
                        </div>                   
                    </div>
                </div>
        </div>


        <div class="c-pay-methods__row c-pay-methods__row-full">
            <h3 class="c-pay-methods__title i-after-information">0% pagando con TDC</h3>
            <div class="c-pay-methods__brands">
                <figure class="c-pay-methods__figure">
                    <img 
                        class="c-pay-methods__img"
                        src="<?php echo $block->getViewFileUrl('images/bank-brands/bancolombia-logo.png') ?>"
                    >
                </figure>
                <figure class="c-pay-methods__figure">
                    <img 
                        class="c-pay-methods__img"
                        src="<?php echo $block->getViewFileUrl('images/bank-brands/davivienda_logo.png') ?>"
                    >
                </figure>
                <figure class="c-pay-methods__figure">
                    <img 
                        class="c-pay-methods__img"
                        src="<?php echo $block->getViewFileUrl('images/bank-brands/banco-de-bogota-logo.png') ?>"
                    >
                </figure>
                <figure class="c-pay-methods__figure">
                    <img 
                        class="c-pay-methods__img"
                        src="<?php echo $block->getViewFileUrl('images/bank-brands/banco-av-villas-logo.png') ?>"
                    >
                </figure>
                <figure class="c-pay-methods__figure">
                    <img 
                        class="c-pay-methods__img"
                        src="<?php echo $block->getViewFileUrl('images/bank-brands/rapi-card-logo.png') ?>"
                    >
                </figure>
                <figure class="c-pay-methods__figure">
                    <img 
                        class="c-pay-methods__img"
                        src="<?php echo $block->getViewFileUrl('images/bank-brands/itau_logo.png') ?>"
                    >
                </figure>
            </div>
        </div>


        <div class="c-pay-methods__row">
            <h3 class="c-pay-methods__title">Garantía</h3>
            <div class="c-pay-methods__slot-wrap c-pay-methods__slot-wrap-gap">
                <div class="c-pay-methods__slot c-pay-methods__slot-margin">
                    <span class="c-pay-methods__ico c-pay-methods__ico_dark i-phone-key"></span>
                    <div class="c-pay-methods__content">
                        <h4 class="c-pay-methods__subtitle c-pay-methods__subtitle-size i-after-information">Cambios y devoluciones</h4>
                        <p class="c-pay-methods__description c-pay-methods__description-size">Recibe el producto que compraste o te devolvemos tu dinero. </p>
                    </div>
                </div>                   
                
            
                <div class="c-pay-methods__slot c-pay-methods__slot-margin">
                    <span class="c-pay-methods__ico c-pay-methods__ico_dark i-phone-key"></span>
                    <div class="c-pay-methods__content">
                        <h4 class="c-pay-methods__subtitle c-pay-methods__subtitle-size i-after-information">Tipo de garantía de marca</h4>
                        <p class="c-pay-methods__description c-pay-methods__description-size">Garantía de 1 año por defectos de frabrica directos, no cubre caídas, fisuras o cualquier tipo de alteración del mismo.</p>
                    </div> 
                </div>

            </div>
        </div>

    </div>
</div>