<!-- Modal lo sentimos -->

<!-- <div class="o-modal modal  u-hidden" id="modal-terms_conditions" data-modal-type="modal-small" >     
    <button class="o-modal__btn-close close-modal i-close" data-modal="modal-terms_conditions">
        <span class="u-hidden">Cerrar</span>
    </button>
    <div class="o-modal__content o-modal__content_center">
        <span class="o-modal__img-ico i-information"></span>
        <header class="o-modal__header">
            <h3 class="o-headline">¡Lo sentimos!</h3>
        </header>
        <p class="c-error-modal__paragraph">
            Por ahora no podrás financiar tu equipo a cuotas, <strong>te invitamos a pagar el valor total del equipo.</strong>
        </p>

        <footer class="o-modal__footer">
            <button class="o-modal__btn o-modal__btn_w260 o-modal__btn_margin0 o-btn">Continuar</button>
        </footer> 
    </div>

</div> -->


<!-- Modal atención -->
<div class="o-modal o-modal_w500 modal  u-hidden" id="modal-terms_conditions" data-modal-type="modal-small" >     
    <button class="o-modal__btn-close close-modal i-close" data-modal="modal-terms_conditions">
        <span class="u-hidden">Cerrar</span>
    </button>
    <div class="o-modal__content o-modal__content_center">

        <header class="o-modal__header">
            <img 
                class="o-modal__img o-modal__img-small" 
                alt="Logo Movistar" 
                src="<?= $this->getViewFileUrl('images/brand-movistar.svg') ?>">
            <h3 class="o-headline">
                ¡Atención!
            </h3>
        </header>

        <div class="o-modal__text-box o-modal__text-box_marginb">
            <p>          
                Te redirigiremos al sitio de Movistar Money para continuar con tu proceso de financiación.
            </p>
        </div>
    </div>

</div>