<div class="o-modal o-modal_w711 modal  u-hidden" id="modal-processing_personal_data" data-modal-type="modal-small" >
    <button class="o-modal__btn-close close-modal i-close" data-modal="modal-processing_personal_data">
        <span class="u-hidden">Cerrar</span>
    </button>
    <div class="o-modal__content o-modal__content_center o-modal__content_w572">

        <header class="o-modal__header">
            <img
                class="o-modal__img o-modal__img-small"
                alt="Logo Movistar"
                src="<?= $this->getViewFileUrl('images/brand-movistar.svg') ?>">
            <h3 class="o-headline o-headline_blue">
                Tratamiento y Protección de Datos de Carácter Personal
            </h3>
        </header>

        <div class="o-modal__text-box o-modal__text-box_text-left">
            <p>
                El titular de los datos personales autoriza a Telefónica (Av. Suba No.114
                A-55 de Bogotá, tel. 091 7050000) para recolectar, almacenar,
                conservar, usar, suprimir, actualizar, compartir y circular a terceros, sus
                datos personales de orden demográfico, económico, biométricos, de
                servicios, comercial y de localización; para obtención y suministro de
                información relativa al cumplimiento de sus obligaciones y el cálculo de
                riesgo económico o crediticio (de manera irrevocable), la publicación de
                directorios telefónicos, la prevención y control de fraudes, y para
                beneficio propio o de terceros con los que Telefónica haya celebrado
                convenio para envío y recepción de cualquier tipo de información, con
                fines comerciales o publicitarios en Colombia o en el exterior. La
                información para el cálculo de riesgo crediticio podrá ser consultada en
                cualquier operador de banco de datos, por las entidades financieras con
                las cuales Telefónica celebre convenios comerciales en favor de los
                titulares. Los datos serán tratados de conformidad con las Políticas para
                el Tratamiento de Datos Personales que se encuentran a disposición de
                los interesados y/o titulares de los datos en la página web
                www.movistar.co El titular de los datos tiene derecho de conocer,
                actualizar, rectificar, suprimir los datos, y revocar la autorización salvo las
                excepciones legales. Los datos biométricos son datos sensibles y el
                titular no está obligado a autorizar su tratamiento, estos serán usados
                para verificación de identidad y suscripción de contratos.
            </p>
        </div>

        <footer class="o-modal__footer">
            <button
                data-modal="modal-processing_personal_data"
                class="o-modal__btn o-modal__btn_w260 o-btn o-btn_height56 o-modal__btn_margin0 o-btn close-modal"
            >
                Cerrar
            </button>
        </footer>
    </div>

</div>