<div class="o-modal modal  u-hidden" id="modal-success_change_address" data-modal-type="modal-large" >   
    <button class="o-modal__btn-close close-modal i-close" data-modal="modal-success_change_address">
        <span class="u-hidden">Cerrar</span>
    </button>
    <div class="o-modal__content o-modal__content_center o-modal__content_w572">
        <header class="o-modal__header">
            <img 
                class="o-modal__img o-modal__img-small" 
                alt="Logo Movistar" 
                src="<?= $this->getViewFileUrl('images/brand-movistar.svg') ?>"
            >
            <h3 class="o-headline o-headline_blue">¡Cambio de dirección exitoso!</h3>
        </header>
        <p>
            Ya puedes continuar con el proceso de compra
        </p>
        <footer class="o-modal__footer">
            <button class="o-btn o-btn_height56 o-btn_full o-btn_w270 close-modal" data-modal="modal-success_change_address" onclick="location.reload()">Aceptar</button>
        </footer> 
    </div>
</div>