<div class="o-canvas">
    
    <span class="o-btn-float i-whatsapp"></span>

    <ul class="c-footer-simple__list-ico">
        <li class="c-footer-simple__ico-item i-badge-percent">
            <strong>Exclusivo Online</strong>
        </li>
        <li class="c-footer-simple__ico-item i-truck">
            <p>
                <strong>Envío GRATIS</strong> a todo Colombia
            </p>
        </li>
        <li class="c-footer-simple__ico-item i-credit-card">
            <p>   
                <strong>Difiere</strong> con  tu tarjeta preferida
            </p>
        </li>
        <li class="c-footer-simple__ico-item i-lock-fill">
            <p>
                Compra de forma <strong>segura</strong>
            </p>
        </li>
    </ul>
    <div class="c-footer-simple__divider">
        <p class="c-footer-simple__copy-right">© 2021 Movistar. Todos los derechos reservados.</p>
        <ul class="c-footer-simple__list">
            <li class="c-footer-simple__item">
                <a class="c-footer-simple__link" href="#">
                    Política de privacidad
                </a>
            </li>
            <li class="c-footer-simple__item">
                <a class="c-footer-simple__link" href="#">
                    Términos y condiciones
                </a>
            </li>
            <li class="c-footer-simple__item">
                <a class="c-footer-simple__link" href="#">
                    Ventas y devoluciones
                </a>
            </li>
            <li class="c-footer-simple__item">
                <a class="c-footer-simple__link" href="#">
                    Política de cookies
                </a>
            </li>
            <li class="c-footer-simple__item">
                <a class="c-footer-simple__link" href="#">
                    Mapa de sitio
                </a>
            </li>
        </ul>
    </div>
</div>

<script src="<?php echo $this->getViewFileUrl('js/show_password.js'); ?>"></script>
<script src="<?php echo $this->getViewFileUrl('js/general/dropdown.js'); ?>"></script>
<script src="<?php echo $this->getViewFileUrl('js/timer.js'); ?>"></script>
<script src="<?php echo $this->getViewFileUrl('js/general/toggle_class.js'); ?>"></script>
