<div class="o-canvas o-canvas_max-width918">
    <div class="is-active">
        <header class="o-header-img u-margin-top-56 u-margin-bottom-56">
            <img 
                class="o-header-img__brand o-header-img__brand_w207" 
                alt="Figura de un hombre levantando una alerta" 
                src="<?= $this->getViewFileUrl('images/figure-men.svg') ?>"
            >
            <h3 class="o-header-img__text o-header-img__text_font40 u-margin-bottom-24">!Woops¡</h3>
            <h1 class="o-header-img__intro">
                <span class="o-header-img__intro_strong">Algo no ha salido según lo planeado y no se puedo completar el pago.</span> 
                Recibirás un correo notificandote de lo sucedido</h1>
            <h2 class="o-header-img__intro o-header-img__intro_dark-blue">Tú número de orden es <span class="o-header-img__intro_strong u-display-inline">20000402123031</span></h2>
        </header>

        <div class="u-text-center u-margin-bottom-56">
            <!-- se añade la clase is-loading a la par de o-btn-icon para dar efecto spin al icono -->
            <a class="o-btn o-btn_full o-btn_w392 o-btn-icon o-btn-icon_font26 i-load-arrow o-btn_height60" href="#">Reintenta el pago</a>
            <a class="o-link u-margin-top-32 u-display-block" href="#">¿Quieres ver el detalle de la operación?</a>
        </div>
        
       
    </div>

</div>